version: "3"
services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    volumes:
      - ./caddy/data:/data
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 80:80
      - 443:443
    env_file: shimmitty.env
    networks:
      - caddy

  shimmie:
    image: shish2k/shimmie2:latest
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./themes/mitty:/app/themes/Mitty
      - ./counters:/app/ext/home/counters/LuckyCharms
    networks:
      - caddy

  memcached:
    image: memcached:alpine
    restart: unless-stopped
    command:
      - --conn-limit=1024
      - --memory-limit=64
      - --threads=4
    networks:
      - caddy

networks:
  caddy:
