services:
  caddy:
    build:
      context: .
      dockerfile: Dockerfile.caddy
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - ./caddy/data:/data
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./geoip:/geoip
      - ./caddy/caddy_pages:/usr/share/caddy
    ports:
      - "80:80"
      - "443:443"
    env_file: shimmitty.env
    networks:
      - caddy

  shimmie:
    image: shish2k/shimmie2:latest
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./themes/mitty:/app/themes/Mitty
      - ./counters:/app/ext/home/counters/LuckyCharms
      - ./shimmie-ext/ReportButton:/app/ext/ReportButton
      - ./shimmie-ext/TermsOfService:/app/ext/TermsOfService
    networks:
      - caddy

  memcached:
    image: memcached:alpine
    restart: unless-stopped
    command:
      - --conn-limit=1024
      - --memory-limit=64
      - --threads=4
    networks:
      - caddy

networks:
  caddy: